spring:
  application:
    name: backend
  
  datasource:
    url: jdbc:postgresql://localhost:5433/PSYCareDB
    username: postgres
    password: 123Andrei
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem